! This file was automatically generated by the f90tools.py Python script
! from the ./utils folder.
! To do any modifications, please modify the YAML files in the ./docs folder or the script directly.
! NOTE THAT the modifications will be erased when you run the Python script again.
! Date: April 09, 2025 15:55

module perturbo_autogen_param
   use pert_const, only: dp
   implicit none
   real(dp), save :: abstol_c !< absolute error tolerance for carrier population for using any SUNDIALS time stepping method.
   real(dp), save :: abstol_ph !< absolute error tolerance for phonon population for using any SUNDIALS time stepping method.
   logical, save :: adapt_smear_eph !< compute scattering electron-phonon channels with adaptive Gaussian smearing based on electron group velocities
   logical, save :: adapt_smear_phph !< compute scattering phonon-phonon channels with adaptive Gaussian smearing based on phonon group velocities
   integer, save :: band_max !< Highest band included.
   integer, save :: band_min !< Lowest band included.
   real(dp), save :: boltz_acc_thr !< Drift acceleration threshold. If specified, the real-time simulation will stop when at least 10 last iterations had a drift acceleration lower than the threshold.
   real(dp), save :: boltz_de !< Energy step for the integrals in the Boltzmann equation of carrier population.
   real(dp), save :: boltz_de_ph !< Energy step for the integrals in the Boltzmann equation of phonon population.
   real(dp), save :: boltz_efield(3) !< External electric field for the ultrafast real-time dynamics.
   real(dp), save :: boltz_emax !< Top of the energy window for the Boltzmann equation.
   real(dp), save :: boltz_emin !< Bottom of the energy window for the Boltzmann equation.
   real(dp), save :: boltz_init_ampl !< Amplitude of the initial distribution, currently implemented for <code><a href=#boltz_init_dist>boltz_init_dist</a>='gaussian'</code>.
   character(len=80), save :: boltz_init_dist !< Initial electron distribution at time zero.
   real(dp), save :: boltz_init_e0 !< Energy parameter used to generate initial distribution. Needs to be specified for <code><a href=#boltz_init_dist>boltz_init_dist</a>='lorentz'</code> (center), <code>'gaussian'</code> (center), or <code>'fermi'</code> (chemical potential).
   real(dp), save :: boltz_init_smear !< The broadening or width of the initial distribution for <code><a href=#boltz_init_dist>boltz_init_dist</a>='lorentz'</code> or <code>'gaussian'</code>, or temperature (in meV) for <code>'fermi'</code>.
   integer, save :: boltz_kdim(3) !< Number of <b>k</b> points along each dimension for the Boltzmann equation.
   logical, save :: boltz_norm_dist !< Normalize the distribution function at each step of the real-time Boltzmann Transport Equation simulation.
   logical, save :: boltz_norm_energy !< Normalize the distribution function of carriers as well as total energy (if phonon population changes with time) at each step of the real-time Boltzmann Transport Equation simulation.
   integer, save :: boltz_nstep !< Number of iterations for solving the Boltzmann transport equation.
   integer, save :: boltz_nstep_min !< Minimum number of iterations of real-time dynamics. Used with <code><a href=#boltz_acc_thr>boltz_acc_thr</a></code>. Will not be applied if <code><a href=#boltz_acc_thr>boltz_acc_thr</a></code> is not specified, in this case, use <code><a href=#boltz_nstep>boltz_nstep</a></code> instead.
   integer, save :: boltz_qdim(3) !< Number of <b>q</b> points along each dimension for the Boltzmann equation. It should be same with boltz_kdim.
   character(len=80), save :: calc_mode !< Calculation mode.
   real(dp), save :: cauchy_scale !< Scale parameter gamma for the Cauchy distribution; used when <code><a href="#sampling">sampling</a>='cauchy'</code>.
   integer, save :: cond_bmin !< the band index of the lowest conduction band
   logical :: converge_diag !<  Not yet
   real(dp), save :: cum_de !< Energy difference. Decide output spectral energy step with spectral : cum_de / spectral_np
   real(dp), save :: cum_inner_emax !< Upper boundry for inner window when do cumulant calculation
   real(dp), save :: cum_inner_emin !< Lower boundry for inner window when do cumulant calculation
   real(dp), save :: cum_outer_emax !< Upper boundry for outer window when do cumulant calculation
   real(dp), save :: cum_outer_emin !< Lower boundry for outer window when do cumulant calculation
   integer, save :: cum_outer_np !< Number of points of outer window
   logical, save :: debug !< Debug mode.
   real(dp), save :: delta_smear !< Smearing for the Dirac delta function for e-ph.
   real(dp), save :: delta_smear_ph !< Smearing for the Dirac delta function for anaharmonic phonons (ph-ph).
   logical, save :: divide_grid !< Determine whether to use a coarser grid to compute phonon-phonon matrix elements.
   logical :: drag !<  Not yet
   logical, save :: dyna_phph !< include time-dependent phonon populations and anharmonic phonon interactions in dynamics.
   logical, save :: find_efermi !< Flag to indicate whether to find the Fermi energy, which means fix the Fermi energy or occupancy.
   character(len=80), save :: fklist !< Name of the file containing the k-point list (in crystal coordiates).
   character(len=80), save :: fqlist !< Name of the file containing the q-point list (in crystal coordiates).
   character(len=80), save :: ftemper !< Name of the file containing values for the temperature (K), chemical potential (eV), and carrier concentration (cm<sup>-2</sup> or cm<sup>-3</sup>).
   logical, save :: full_ite !< Solve BTE with both E- and T-fields iteratively.
   logical, save :: hole !< Set to .true. for calculations on hole carriers.
   real(dp), save :: hs !< slow time step size for MRI in SUNDIALS time stepping module.
   logical, save :: load_scatter_eph !< Read the e-ph matrix elements from the files in tmp_dir. Used for <code><a href=#calc_mode>calc_mode</a>='trans'</code> and <code><a href=#calc_mode>calc_mode</a>='dynamics'.
   logical, save :: load_scatter_ph3 !< Read the ph-ph matrix elements from the files in tmp_dir. Used for <code><a href=#calc_mode>calc_mode</a>='phonlife'</code> and <code><a href=#calc_mode>calc_mode</a>='dynamics'.
   integer, save :: nphstep !< evolve phonons every <code>nphstep</code> of time steps for rk4 or euler solvers.
   integer, save :: nsamples !< Number of q-points for the summation over the q-points in imsigma calculation.
   integer, save :: output_nstep !< Print out the results every <code>output_nstep</code> time steps.
   logical :: ph_e !<  Not yet
   integer, save :: ph_mode_exclude_ranges(30, 2) !< Specify the phonon modes to exclude in rt-BTE: the g2 factor will be set to zero for these modes. The modes to exclude are specified with ranges, e.g. to exclude modes from 2 to 5, write in the input file: <code>ph_mode_exclude_ranges(1,:)=2,5 </code>. To add another range to exclude, specify <code>ph_mode_exclude_ranges(2,:)=7,10 </code>. One can use up to 30 ranges. To exclude one mode, set first and second number to the phonon mode index. The indices of the phonon modes to exclude must be smaller than the total number of modes in a system.
   logical, save :: ph_vel_numerical !< Use numerical velocity for phonon group velocity
   real(dp), save :: phfreq_cutoff !< Phonon energy threshold. Phonons with energy smaller than phfreq_cutoff will be excluded.
   real(dp), save :: phfreq_cutoff_ph !< Phonon energy threshold. Phonons with energy smaller than phfreq_cutoff_ph will be excluded for anharmonic phonon scattering.
   character(len=80), save :: polar_split !< Polar correction mode.
   character(len=80), save :: prefix !< Job name prefix. It should be the same as the prefix used in QE.
   real(dp), save :: pulse !< optical transition pulse energy in eV
   logical, save :: pump_pulse !< During first <code>pulse_num_steps</code> of dynamics, add extra occupations (hence the name, 'pump'). A file <code>pump_pulse.h5</code> (or specified name with <code>pump_pulse_fname</code>) must be present in the directory and it must have the following datasets: <code>pulse_num_steps</code>, <code>pulse_snap_t_[...]</code>, <code>time_step</code>.
   character(len=80), save :: pump_pulse_fname !< Name of HDF5 file containing pump pulse information, refer to <code><a href=#pump_pulse>pump_pulse</a></code>.
   real(dp), save :: retol !< relative error tolerance for both carrier and phonon populations using any SUNDIALS time stepping method.
   character(len=80), save :: sampling !< Random q points sampling method.
   character(len=10), save :: scat_impl !< Specify which carrier-dynamics implementation to use, either 'std' for the standard CPU-friendly implementation, or 'tgt' for the GPU-friendly target-oriented implementation.
   logical :: setup_rmap !<  Not yet
   character(len=80), save :: solver !< Solver type for the Boltzmann transport equation.
   real(dp), save :: spectral_emax !< upper boundry of spectral energy scale
   real(dp), save :: spectral_emin !< lower boundry of spectral energy scale
   integer, save :: spectral_np !< Number of points in the energy window. Decide output spectral energy step with cum_de: cum_de / spectral_np
   character(len=80), save :: sun_method !< Time stepping method for SUNDIALS for Boltzmann transport equation, only used when solver='sundials'
   integer, save :: sundials_mxsteps !< maximum number of SUNDIALS internal steps per time step.
   logical :: symm !<  Not yet
   real(dp), save :: time_step !< Time step for the carrier dynamics.
   character(len=80), save :: tmp_dir !< The directory where the e-ph matrix elements are stored when <code><a href=#calc_mode>calc_mode</a>='trans'</code>.
   real(dp), save :: trans_thr !< Threshold for the iterative procedure.
   logical, save :: use_mem !< Flag for using memory or not and only used in boltz_scatter
   character(len=80), save :: yaml_fname !< Name of the YAML output file. If the parameter (<code>yaml_fname</code>) is not changed by the user, the output name of the YAML file will be {prefix}_{calc_mode}.yml. For example, for Si bands calculation, the YAML file would be called si_bands.yml.

   real(dp), save :: abstol_c_beforeconv !< absolute error tolerance for carrier population for using any SUNDIALS time stepping method. (before conversion of the unit)
   real(dp), save :: abstol_ph_beforeconv !< absolute error tolerance for phonon population for using any SUNDIALS time stepping method. (before conversion of the unit)
   logical, save :: adapt_smear_eph_beforeconv !< compute scattering electron-phonon channels with adaptive Gaussian smearing based on electron group velocities (before conversion of the unit)
   logical, save :: adapt_smear_phph_beforeconv !< compute scattering phonon-phonon channels with adaptive Gaussian smearing based on phonon group velocities (before conversion of the unit)
   integer, save :: band_max_beforeconv !< Highest band included. (before conversion of the unit)
   integer, save :: band_min_beforeconv !< Lowest band included. (before conversion of the unit)
   real(dp), save :: boltz_acc_thr_beforeconv !< Drift acceleration threshold. If specified, the real-time simulation will stop when at least 10 last iterations had a drift acceleration lower than the threshold. (before conversion of the unit)
   real(dp), save :: boltz_de_beforeconv !< Energy step for the integrals in the Boltzmann equation of carrier population. (before conversion of the unit)
   real(dp), save :: boltz_de_ph_beforeconv !< Energy step for the integrals in the Boltzmann equation of phonon population. (before conversion of the unit)
   real(dp), save :: boltz_efield_beforeconv(3) !< External electric field for the ultrafast real-time dynamics. (before conversion of the unit)
   real(dp), save :: boltz_emax_beforeconv !< Top of the energy window for the Boltzmann equation. (before conversion of the unit)
   real(dp), save :: boltz_emin_beforeconv !< Bottom of the energy window for the Boltzmann equation. (before conversion of the unit)
   real(dp), save :: boltz_init_ampl_beforeconv !< Amplitude of the initial distribution, currently implemented for <code><a href=#boltz_init_dist>boltz_init_dist</a>='gaussian'</code>. (before conversion of the unit)
   character(len=80), save :: boltz_init_dist_beforeconv !< Initial electron distribution at time zero. (before conversion of the unit)
   real(dp), save :: boltz_init_e0_beforeconv !< Energy parameter used to generate initial distribution. Needs to be specified for <code><a href=#boltz_init_dist>boltz_init_dist</a>='lorentz'</code> (center), <code>'gaussian'</code> (center), or <code>'fermi'</code> (chemical potential). (before conversion of the unit)
   real(dp), save :: boltz_init_smear_beforeconv !< The broadening or width of the initial distribution for <code><a href=#boltz_init_dist>boltz_init_dist</a>='lorentz'</code> or <code>'gaussian'</code>, or temperature (in meV) for <code>'fermi'</code>. (before conversion of the unit)
   integer, save :: boltz_kdim_beforeconv(3) !< Number of <b>k</b> points along each dimension for the Boltzmann equation. (before conversion of the unit)
   logical, save :: boltz_norm_dist_beforeconv !< Normalize the distribution function at each step of the real-time Boltzmann Transport Equation simulation. (before conversion of the unit)
   logical, save :: boltz_norm_energy_beforeconv !< Normalize the distribution function of carriers as well as total energy (if phonon population changes with time) at each step of the real-time Boltzmann Transport Equation simulation. (before conversion of the unit)
   integer, save :: boltz_nstep_beforeconv !< Number of iterations for solving the Boltzmann transport equation. (before conversion of the unit)
   integer, save :: boltz_nstep_min_beforeconv !< Minimum number of iterations of real-time dynamics. Used with <code><a href=#boltz_acc_thr>boltz_acc_thr</a></code>. Will not be applied if <code><a href=#boltz_acc_thr>boltz_acc_thr</a></code> is not specified, in this case, use <code><a href=#boltz_nstep>boltz_nstep</a></code> instead. (before conversion of the unit)
   integer, save :: boltz_qdim_beforeconv(3) !< Number of <b>q</b> points along each dimension for the Boltzmann equation. It should be same with boltz_kdim. (before conversion of the unit)
   character(len=80), save :: calc_mode_beforeconv !< Calculation mode. (before conversion of the unit)
   real(dp), save :: cauchy_scale_beforeconv !< Scale parameter gamma for the Cauchy distribution; used when <code><a href="#sampling">sampling</a>='cauchy'</code>. (before conversion of the unit)
   integer, save :: cond_bmin_beforeconv !< the band index of the lowest conduction band (before conversion of the unit)
   logical :: converge_diag_beforeconv !<  Not yet (before conversion of the unit)
   real(dp), save :: cum_de_beforeconv !< Energy difference. Decide output spectral energy step with spectral : cum_de / spectral_np (before conversion of the unit)
   real(dp), save :: cum_inner_emax_beforeconv !< Upper boundry for inner window when do cumulant calculation (before conversion of the unit)
   real(dp), save :: cum_inner_emin_beforeconv !< Lower boundry for inner window when do cumulant calculation (before conversion of the unit)
   real(dp), save :: cum_outer_emax_beforeconv !< Upper boundry for outer window when do cumulant calculation (before conversion of the unit)
   real(dp), save :: cum_outer_emin_beforeconv !< Lower boundry for outer window when do cumulant calculation (before conversion of the unit)
   integer, save :: cum_outer_np_beforeconv !< Number of points of outer window (before conversion of the unit)
   logical, save :: debug_beforeconv !< Debug mode. (before conversion of the unit)
   real(dp), save :: delta_smear_beforeconv !< Smearing for the Dirac delta function for e-ph. (before conversion of the unit)
   real(dp), save :: delta_smear_ph_beforeconv !< Smearing for the Dirac delta function for anaharmonic phonons (ph-ph). (before conversion of the unit)
   logical, save :: divide_grid_beforeconv !< Determine whether to use a coarser grid to compute phonon-phonon matrix elements. (before conversion of the unit)
   logical :: drag_beforeconv !<  Not yet (before conversion of the unit)
   logical, save :: dyna_phph_beforeconv !< include time-dependent phonon populations and anharmonic phonon interactions in dynamics. (before conversion of the unit)
   logical, save :: find_efermi_beforeconv !< Flag to indicate whether to find the Fermi energy, which means fix the Fermi energy or occupancy. (before conversion of the unit)
   character(len=80), save :: fklist_beforeconv !< Name of the file containing the k-point list (in crystal coordiates). (before conversion of the unit)
   character(len=80), save :: fqlist_beforeconv !< Name of the file containing the q-point list (in crystal coordiates). (before conversion of the unit)
   character(len=80), save :: ftemper_beforeconv !< Name of the file containing values for the temperature (K), chemical potential (eV), and carrier concentration (cm<sup>-2</sup> or cm<sup>-3</sup>). (before conversion of the unit)
   logical, save :: full_ite_beforeconv !< Solve BTE with both E- and T-fields iteratively. (before conversion of the unit)
   logical, save :: hole_beforeconv !< Set to .true. for calculations on hole carriers. (before conversion of the unit)
   real(dp), save :: hs_beforeconv !< slow time step size for MRI in SUNDIALS time stepping module. (before conversion of the unit)
   logical, save :: load_scatter_eph_beforeconv !< Read the e-ph matrix elements from the files in tmp_dir. Used for <code><a href=#calc_mode>calc_mode</a>='trans'</code> and <code><a href=#calc_mode>calc_mode</a>='dynamics'. (before conversion of the unit)
   logical, save :: load_scatter_ph3_beforeconv !< Read the ph-ph matrix elements from the files in tmp_dir. Used for <code><a href=#calc_mode>calc_mode</a>='phonlife'</code> and <code><a href=#calc_mode>calc_mode</a>='dynamics'. (before conversion of the unit)
   integer, save :: nphstep_beforeconv !< evolve phonons every <code>nphstep</code> of time steps for rk4 or euler solvers. (before conversion of the unit)
   integer, save :: nsamples_beforeconv !< Number of q-points for the summation over the q-points in imsigma calculation. (before conversion of the unit)
   integer, save :: output_nstep_beforeconv !< Print out the results every <code>output_nstep</code> time steps. (before conversion of the unit)
   logical :: ph_e_beforeconv !<  Not yet (before conversion of the unit)
   integer, save :: ph_mode_exclude_ranges_beforeconv(30, 2) !< Specify the phonon modes to exclude in rt-BTE: the g2 factor will be set to zero for these modes. The modes to exclude are specified with ranges, e.g. to exclude modes from 2 to 5, write in the input file: <code>ph_mode_exclude_ranges(1,:)=2,5 </code>. To add another range to exclude, specify <code>ph_mode_exclude_ranges(2,:)=7,10 </code>. One can use up to 30 ranges. To exclude one mode, set first and second number to the phonon mode index. The indices of the phonon modes to exclude must be smaller than the total number of modes in a system. (before conversion of the unit)
   logical, save :: ph_vel_numerical_beforeconv !< Use numerical velocity for phonon group velocity (before conversion of the unit)
   real(dp), save :: phfreq_cutoff_beforeconv !< Phonon energy threshold. Phonons with energy smaller than phfreq_cutoff will be excluded. (before conversion of the unit)
   real(dp), save :: phfreq_cutoff_ph_beforeconv !< Phonon energy threshold. Phonons with energy smaller than phfreq_cutoff_ph will be excluded for anharmonic phonon scattering. (before conversion of the unit)
   character(len=80), save :: polar_split_beforeconv !< Polar correction mode. (before conversion of the unit)
   character(len=80), save :: prefix_beforeconv !< Job name prefix. It should be the same as the prefix used in QE. (before conversion of the unit)
   real(dp), save :: pulse_beforeconv !< optical transition pulse energy in eV (before conversion of the unit)
   logical, save :: pump_pulse_beforeconv !< During first <code>pulse_num_steps</code> of dynamics, add extra occupations (hence the name, 'pump'). A file <code>pump_pulse.h5</code> (or specified name with <code>pump_pulse_fname</code>) must be present in the directory and it must have the following datasets: <code>pulse_num_steps</code>, <code>pulse_snap_t_[...]</code>, <code>time_step</code>. (before conversion of the unit)
   character(len=80), save :: pump_pulse_fname_beforeconv !< Name of HDF5 file containing pump pulse information, refer to <code><a href=#pump_pulse>pump_pulse</a></code>. (before conversion of the unit)
   real(dp), save :: retol_beforeconv !< relative error tolerance for both carrier and phonon populations using any SUNDIALS time stepping method. (before conversion of the unit)
   character(len=80), save :: sampling_beforeconv !< Random q points sampling method. (before conversion of the unit)
   character(len=10), save :: scat_impl_beforeconv !< Specify which carrier-dynamics implementation to use, either 'std' for the standard CPU-friendly implementation, or 'tgt' for the GPU-friendly target-oriented implementation. (before conversion of the unit)
   logical :: setup_rmap_beforeconv !<  Not yet (before conversion of the unit)
   character(len=80), save :: solver_beforeconv !< Solver type for the Boltzmann transport equation. (before conversion of the unit)
   real(dp), save :: spectral_emax_beforeconv !< upper boundry of spectral energy scale (before conversion of the unit)
   real(dp), save :: spectral_emin_beforeconv !< lower boundry of spectral energy scale (before conversion of the unit)
   integer, save :: spectral_np_beforeconv !< Number of points in the energy window. Decide output spectral energy step with cum_de: cum_de / spectral_np (before conversion of the unit)
   character(len=80), save :: sun_method_beforeconv !< Time stepping method for SUNDIALS for Boltzmann transport equation, only used when solver='sundials' (before conversion of the unit)
   integer, save :: sundials_mxsteps_beforeconv !< maximum number of SUNDIALS internal steps per time step. (before conversion of the unit)
   logical :: symm_beforeconv !<  Not yet (before conversion of the unit)
   real(dp), save :: time_step_beforeconv !< Time step for the carrier dynamics. (before conversion of the unit)
   character(len=80), save :: tmp_dir_beforeconv !< The directory where the e-ph matrix elements are stored when <code><a href=#calc_mode>calc_mode</a>='trans'</code>. (before conversion of the unit)
   real(dp), save :: trans_thr_beforeconv !< Threshold for the iterative procedure. (before conversion of the unit)
   logical, save :: use_mem_beforeconv !< Flag for using memory or not and only used in boltz_scatter (before conversion of the unit)
   character(len=80), save :: yaml_fname_beforeconv !< Name of the YAML output file. If the parameter (<code>yaml_fname</code>) is not changed by the user, the output name of the YAML file will be {prefix}_{calc_mode}.yml. For example, for Si bands calculation, the YAML file would be called si_bands.yml. (before conversion of the unit)

   namelist / perturbo / & 
      abstol_c, & 
      abstol_ph, & 
      adapt_smear_eph, & 
      adapt_smear_phph, & 
      band_max, & 
      band_min, & 
      boltz_acc_thr, & 
      boltz_de, & 
      boltz_de_ph, & 
      boltz_efield, & 
      boltz_emax, & 
      boltz_emin, & 
      boltz_init_ampl, & 
      boltz_init_dist, & 
      boltz_init_e0, & 
      boltz_init_smear, & 
      boltz_kdim, & 
      boltz_norm_dist, & 
      boltz_norm_energy, & 
      boltz_nstep, & 
      boltz_nstep_min, & 
      boltz_qdim, & 
      calc_mode, & 
      cauchy_scale, & 
      cond_bmin, & 
      converge_diag, & 
      cum_de, & 
      cum_inner_emax, & 
      cum_inner_emin, & 
      cum_outer_emax, & 
      cum_outer_emin, & 
      cum_outer_np, & 
      debug, & 
      delta_smear, & 
      delta_smear_ph, & 
      divide_grid, & 
      drag, & 
      dyna_phph, & 
      find_efermi, & 
      fklist, & 
      fqlist, & 
      ftemper, & 
      full_ite, & 
      hole, & 
      hs, & 
      load_scatter_eph, & 
      load_scatter_ph3, & 
      nphstep, & 
      nsamples, & 
      output_nstep, & 
      ph_e, & 
      ph_mode_exclude_ranges, & 
      ph_vel_numerical, & 
      phfreq_cutoff, & 
      phfreq_cutoff_ph, & 
      polar_split, & 
      prefix, & 
      pulse, & 
      pump_pulse, & 
      pump_pulse_fname, & 
      retol, & 
      sampling, & 
      scat_impl, & 
      setup_rmap, & 
      solver, & 
      spectral_emax, & 
      spectral_emin, & 
      spectral_np, & 
      sun_method, & 
      sundials_mxsteps, & 
      symm, & 
      time_step, & 
      tmp_dir, & 
      trans_thr, & 
      use_mem, & 
      yaml_fname

contains
subroutine autogen_init_input_param()
   implicit none
   abstol_c = 1e-05_dp
   abstol_ph = 1e-05_dp
   adapt_smear_eph = .false.
   adapt_smear_phph = .false.
   band_max = 9999999
   band_min = 1
   boltz_acc_thr = 0.0_dp
   boltz_de = 1.0_dp
   boltz_de_ph = 0.1_dp
   boltz_efield = [0.0, 0.0, 0.0]
   boltz_emax = 9999.0_dp
   boltz_emin = -9999.0_dp
   boltz_init_ampl = 0.1_dp
   boltz_init_dist = ''
   boltz_init_e0 = -9999.0_dp
   boltz_init_smear = 20.0_dp
   boltz_kdim = [1,1,1]
   boltz_norm_dist = .false.
   boltz_norm_energy = .false.
   boltz_nstep = 0
   boltz_nstep_min = 1
   boltz_qdim = [0,0,0]
   calc_mode = ''
   cauchy_scale = 0.05_dp
   cond_bmin = 1
   converge_diag = .false.
   cum_de = 0.1_dp
   cum_inner_emax = 0.1_dp
   cum_inner_emin = -0.1_dp
   cum_outer_emax = 0.1_dp
   cum_outer_emin = -0.1_dp
   cum_outer_np = 1
   debug = .false.
   delta_smear = 10.0_dp
   delta_smear_ph = 2.0_dp
   divide_grid = .false.
   drag = .false.
   dyna_phph = .false.
   find_efermi = .false.
   fklist = ''
   fqlist = ''
   ftemper = ''
   full_ite = .true.
   hole = .false.
   hs = 1.0_dp
   load_scatter_eph = .false.
   load_scatter_ph3 = .false.
   nphstep = 1
   nsamples = 100000
   output_nstep = 1
   ph_e = .false.
   ph_mode_exclude_ranges = -1
   ph_vel_numerical = .true.
   phfreq_cutoff = 1.0_dp
   phfreq_cutoff_ph = 1.0_dp
   polar_split = ''
   prefix = ''
   pulse = 0.1_dp
   pump_pulse = .false.
   pump_pulse_fname = 'pump_pulse.h5'
   retol = 0.001_dp
   sampling = 'uniform'
   scat_impl = 'std'
   setup_rmap = .false.
   solver = 'rk4'
   spectral_emax = 0.1_dp
   spectral_emin = -0.1_dp
   spectral_np = 1
   sun_method = 'ark'
   sundials_mxsteps = 500
   symm = .false.
   time_step = 1.0_dp
   tmp_dir = '.'
   trans_thr = 0.002_dp
   use_mem = .true.
   yaml_fname = 'pert_output.yml'

end subroutine autogen_init_input_param

subroutine autogen_bcast_input_param()
   use qe_mpi_mod, only: meta_ionode_id, world_comm, mp_bcast
   implicit none

   call mp_bcast(abstol_c,meta_ionode_id,world_comm)
   call mp_bcast(abstol_ph,meta_ionode_id,world_comm)
   call mp_bcast(adapt_smear_eph,meta_ionode_id,world_comm)
   call mp_bcast(adapt_smear_phph,meta_ionode_id,world_comm)
   call mp_bcast(band_max,meta_ionode_id,world_comm)
   call mp_bcast(band_min,meta_ionode_id,world_comm)
   call mp_bcast(boltz_acc_thr,meta_ionode_id,world_comm)
   call mp_bcast(boltz_de,meta_ionode_id,world_comm)
   call mp_bcast(boltz_de_ph,meta_ionode_id,world_comm)
   call mp_bcast(boltz_efield,meta_ionode_id,world_comm)
   call mp_bcast(boltz_emax,meta_ionode_id,world_comm)
   call mp_bcast(boltz_emin,meta_ionode_id,world_comm)
   call mp_bcast(boltz_init_ampl,meta_ionode_id,world_comm)
   call mp_bcast(boltz_init_dist,meta_ionode_id,world_comm)
   call mp_bcast(boltz_init_e0,meta_ionode_id,world_comm)
   call mp_bcast(boltz_init_smear,meta_ionode_id,world_comm)
   call mp_bcast(boltz_kdim,meta_ionode_id,world_comm)
   call mp_bcast(boltz_norm_dist,meta_ionode_id,world_comm)
   call mp_bcast(boltz_norm_energy,meta_ionode_id,world_comm)
   call mp_bcast(boltz_nstep,meta_ionode_id,world_comm)
   call mp_bcast(boltz_nstep_min,meta_ionode_id,world_comm)
   call mp_bcast(boltz_qdim,meta_ionode_id,world_comm)
   call mp_bcast(calc_mode,meta_ionode_id,world_comm)
   call mp_bcast(cauchy_scale,meta_ionode_id,world_comm)
   call mp_bcast(cond_bmin,meta_ionode_id,world_comm)
   call mp_bcast(converge_diag,meta_ionode_id,world_comm)
   call mp_bcast(cum_de,meta_ionode_id,world_comm)
   call mp_bcast(cum_inner_emax,meta_ionode_id,world_comm)
   call mp_bcast(cum_inner_emin,meta_ionode_id,world_comm)
   call mp_bcast(cum_outer_emax,meta_ionode_id,world_comm)
   call mp_bcast(cum_outer_emin,meta_ionode_id,world_comm)
   call mp_bcast(cum_outer_np,meta_ionode_id,world_comm)
   call mp_bcast(debug,meta_ionode_id,world_comm)
   call mp_bcast(delta_smear,meta_ionode_id,world_comm)
   call mp_bcast(delta_smear_ph,meta_ionode_id,world_comm)
   call mp_bcast(divide_grid,meta_ionode_id,world_comm)
   call mp_bcast(drag,meta_ionode_id,world_comm)
   call mp_bcast(dyna_phph,meta_ionode_id,world_comm)
   call mp_bcast(find_efermi,meta_ionode_id,world_comm)
   call mp_bcast(fklist,meta_ionode_id,world_comm)
   call mp_bcast(fqlist,meta_ionode_id,world_comm)
   call mp_bcast(ftemper,meta_ionode_id,world_comm)
   call mp_bcast(full_ite,meta_ionode_id,world_comm)
   call mp_bcast(hole,meta_ionode_id,world_comm)
   call mp_bcast(hs,meta_ionode_id,world_comm)
   call mp_bcast(load_scatter_eph,meta_ionode_id,world_comm)
   call mp_bcast(load_scatter_ph3,meta_ionode_id,world_comm)
   call mp_bcast(nphstep,meta_ionode_id,world_comm)
   call mp_bcast(nsamples,meta_ionode_id,world_comm)
   call mp_bcast(output_nstep,meta_ionode_id,world_comm)
   call mp_bcast(ph_e,meta_ionode_id,world_comm)
   call mp_bcast(ph_mode_exclude_ranges,meta_ionode_id,world_comm)
   call mp_bcast(ph_vel_numerical,meta_ionode_id,world_comm)
   call mp_bcast(phfreq_cutoff,meta_ionode_id,world_comm)
   call mp_bcast(phfreq_cutoff_ph,meta_ionode_id,world_comm)
   call mp_bcast(polar_split,meta_ionode_id,world_comm)
   call mp_bcast(prefix,meta_ionode_id,world_comm)
   call mp_bcast(pulse,meta_ionode_id,world_comm)
   call mp_bcast(pump_pulse,meta_ionode_id,world_comm)
   call mp_bcast(pump_pulse_fname,meta_ionode_id,world_comm)
   call mp_bcast(retol,meta_ionode_id,world_comm)
   call mp_bcast(sampling,meta_ionode_id,world_comm)
   call mp_bcast(scat_impl,meta_ionode_id,world_comm)
   call mp_bcast(setup_rmap,meta_ionode_id,world_comm)
   call mp_bcast(solver,meta_ionode_id,world_comm)
   call mp_bcast(spectral_emax,meta_ionode_id,world_comm)
   call mp_bcast(spectral_emin,meta_ionode_id,world_comm)
   call mp_bcast(spectral_np,meta_ionode_id,world_comm)
   call mp_bcast(sun_method,meta_ionode_id,world_comm)
   call mp_bcast(sundials_mxsteps,meta_ionode_id,world_comm)
   call mp_bcast(symm,meta_ionode_id,world_comm)
   call mp_bcast(time_step,meta_ionode_id,world_comm)
   call mp_bcast(tmp_dir,meta_ionode_id,world_comm)
   call mp_bcast(trans_thr,meta_ionode_id,world_comm)
   call mp_bcast(use_mem,meta_ionode_id,world_comm)
   call mp_bcast(yaml_fname,meta_ionode_id,world_comm)

end subroutine autogen_bcast_input_param

subroutine autogen_input_param_beforeconv()
   implicit none
   abstol_c_beforeconv = abstol_c
   abstol_ph_beforeconv = abstol_ph
   adapt_smear_eph_beforeconv = adapt_smear_eph
   adapt_smear_phph_beforeconv = adapt_smear_phph
   band_max_beforeconv = band_max
   band_min_beforeconv = band_min
   boltz_acc_thr_beforeconv = boltz_acc_thr
   boltz_de_beforeconv = boltz_de
   boltz_de_ph_beforeconv = boltz_de_ph
   boltz_efield_beforeconv = boltz_efield
   boltz_emax_beforeconv = boltz_emax
   boltz_emin_beforeconv = boltz_emin
   boltz_init_ampl_beforeconv = boltz_init_ampl
   boltz_init_dist_beforeconv = boltz_init_dist
   boltz_init_e0_beforeconv = boltz_init_e0
   boltz_init_smear_beforeconv = boltz_init_smear
   boltz_kdim_beforeconv = boltz_kdim
   boltz_norm_dist_beforeconv = boltz_norm_dist
   boltz_norm_energy_beforeconv = boltz_norm_energy
   boltz_nstep_beforeconv = boltz_nstep
   boltz_nstep_min_beforeconv = boltz_nstep_min
   boltz_qdim_beforeconv = boltz_qdim
   calc_mode_beforeconv = calc_mode
   cauchy_scale_beforeconv = cauchy_scale
   cond_bmin_beforeconv = cond_bmin
   converge_diag_beforeconv = converge_diag
   cum_de_beforeconv = cum_de
   cum_inner_emax_beforeconv = cum_inner_emax
   cum_inner_emin_beforeconv = cum_inner_emin
   cum_outer_emax_beforeconv = cum_outer_emax
   cum_outer_emin_beforeconv = cum_outer_emin
   cum_outer_np_beforeconv = cum_outer_np
   debug_beforeconv = debug
   delta_smear_beforeconv = delta_smear
   delta_smear_ph_beforeconv = delta_smear_ph
   divide_grid_beforeconv = divide_grid
   drag_beforeconv = drag
   dyna_phph_beforeconv = dyna_phph
   find_efermi_beforeconv = find_efermi
   fklist_beforeconv = fklist
   fqlist_beforeconv = fqlist
   ftemper_beforeconv = ftemper
   full_ite_beforeconv = full_ite
   hole_beforeconv = hole
   hs_beforeconv = hs
   load_scatter_eph_beforeconv = load_scatter_eph
   load_scatter_ph3_beforeconv = load_scatter_ph3
   nphstep_beforeconv = nphstep
   nsamples_beforeconv = nsamples
   output_nstep_beforeconv = output_nstep
   ph_e_beforeconv = ph_e
   ph_mode_exclude_ranges_beforeconv = ph_mode_exclude_ranges
   ph_vel_numerical_beforeconv = ph_vel_numerical
   phfreq_cutoff_beforeconv = phfreq_cutoff
   phfreq_cutoff_ph_beforeconv = phfreq_cutoff_ph
   polar_split_beforeconv = polar_split
   prefix_beforeconv = prefix
   pulse_beforeconv = pulse
   pump_pulse_beforeconv = pump_pulse
   pump_pulse_fname_beforeconv = pump_pulse_fname
   retol_beforeconv = retol
   sampling_beforeconv = sampling
   scat_impl_beforeconv = scat_impl
   setup_rmap_beforeconv = setup_rmap
   solver_beforeconv = solver
   spectral_emax_beforeconv = spectral_emax
   spectral_emin_beforeconv = spectral_emin
   spectral_np_beforeconv = spectral_np
   sun_method_beforeconv = sun_method
   sundials_mxsteps_beforeconv = sundials_mxsteps
   symm_beforeconv = symm
   time_step_beforeconv = time_step
   tmp_dir_beforeconv = tmp_dir
   trans_thr_beforeconv = trans_thr
   use_mem_beforeconv = use_mem
   yaml_fname_beforeconv = yaml_fname

end subroutine autogen_input_param_beforeconv

end module perturbo_autogen_param
