! This file was automatically generated by the f90tools.py Python script
! from the ./utils folder.
! To do any modifications, please modify the YAML files in the ./docs folder or the script directly.
! NOTE THAT the modifications will be erased when you run the Python script again.
! Date: February 16, 2024 10:29

module perturbo_autogen_output_yaml
   use yaml_utils, only: ymlout, python_bool
   use pert_param
   implicit none
   private

   public :: auto_output_beforeconv_to_yaml
   public :: auto_output_afterconv_to_yaml

contains
subroutine auto_output_afterconv_to_yaml()
   implicit none
   write(ymlout,'(6x, a, 10x, es23.16)') 'abstol_c:', abstol_c
   write(ymlout,'(6x, a, 10x, es23.16)') 'abstol_ph:', abstol_ph
   write(ymlout,'(6x, a, 10x, a)') 'adapt_smear_eph:', python_bool(adapt_smear_eph)
   write(ymlout,'(6x, a, 10x, a)') 'adapt_smear_phph:', python_bool(adapt_smear_phph)
   write(ymlout,'(6x, a, 10x, i10)') 'band_max:', band_max
   write(ymlout,'(6x, a, 10x, i10)') 'band_min:', band_min
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_acc_thr:', boltz_acc_thr
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_de:', boltz_de
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_de_ph:', boltz_de_ph
   write(ymlout,'(6x, a, 10x, "[",3(es23.16,","2x),"]")') 'boltz_efield:', boltz_efield
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_emax:', boltz_emax
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_emin:', boltz_emin
   write(ymlout,'(6x, a, 10x, a)') 'boltz_init_dist:', trim(boltz_init_dist)
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_init_e0:', boltz_init_e0
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_init_smear:', boltz_init_smear
   write(ymlout,'(6x, a, 10x, "[",3(i10,","2x),"]")') 'boltz_kdim:', boltz_kdim
   write(ymlout,'(6x, a, 10x, a)') 'boltz_norm_dist:', python_bool(boltz_norm_dist)
   write(ymlout,'(6x, a, 10x, a)') 'boltz_norm_energy:', python_bool(boltz_norm_energy)
   write(ymlout,'(6x, a, 10x, i10)') 'boltz_nstep:', boltz_nstep
   write(ymlout,'(6x, a, 10x, i10)') 'boltz_nstep_min:', boltz_nstep_min
   write(ymlout,'(6x, a, 10x, "[",3(i10,","2x),"]")') 'boltz_qdim:', boltz_qdim
   write(ymlout,'(6x, a, 10x, a)') 'calc_mode:', trim(calc_mode)
   write(ymlout,'(6x, a, 10x, es23.16)') 'cauchy_scale:', cauchy_scale
   write(ymlout,'(6x, a, 10x, es23.16)') 'cum_de:', cum_de
   write(ymlout,'(6x, a, 10x, es23.16)') 'cum_inner_emax:', cum_inner_emax
   write(ymlout,'(6x, a, 10x, es23.16)') 'cum_inner_emin:', cum_inner_emin
   write(ymlout,'(6x, a, 10x, es23.16)') 'cum_outer_emax:', cum_outer_emax
   write(ymlout,'(6x, a, 10x, es23.16)') 'cum_outer_emin:', cum_outer_emin
   write(ymlout,'(6x, a, 10x, i10)') 'cum_outer_np:', cum_outer_np
   write(ymlout,'(6x, a, 10x, a)') 'debug:', python_bool(debug)
   write(ymlout,'(6x, a, 10x, es23.16)') 'delta_smear:', delta_smear
   write(ymlout,'(6x, a, 10x, es23.16)') 'delta_smear_ph:', delta_smear_ph
   write(ymlout,'(6x, a, 10x, a)') 'divide_grid:', python_bool(divide_grid)
   write(ymlout,'(6x, a, 10x, a)') 'dyna_phph:', python_bool(dyna_phph)
   write(ymlout,'(6x, a, 10x, a)') 'find_efermi:', python_bool(find_efermi)
   write(ymlout,'(6x, a, 10x, a)') 'fklist:', trim(fklist)
   write(ymlout,'(6x, a, 10x, a)') 'fqlist:', trim(fqlist)
   write(ymlout,'(6x, a, 10x, a)') 'ftemper:', trim(ftemper)
   write(ymlout,'(6x, a, 10x, a)') 'full_ite:', python_bool(full_ite)
   write(ymlout,'(6x, a, 10x, a)') 'hole:', python_bool(hole)
   write(ymlout,'(6x, a, 10x, es23.16)') 'hs:', hs
   write(ymlout,'(6x, a, 10x, a)') 'load_scatter_eph:', python_bool(load_scatter_eph)
   write(ymlout,'(6x, a, 10x, a)') 'load_scatter_ph3:', python_bool(load_scatter_ph3)
   write(ymlout,'(6x, a, 10x, i10)') 'nphstep:', nphstep
   write(ymlout,'(6x, a, 10x, i10)') 'nsamples:', nsamples
   write(ymlout,'(6x, a, 10x, i10)') 'output_nstep:', output_nstep
   write(ymlout,'(6x, a, 10x, es23.16)') 'phfreq_cutoff:', phfreq_cutoff
   write(ymlout,'(6x, a, 10x, es23.16)') 'phfreq_cutoff_ph:', phfreq_cutoff_ph
   write(ymlout,'(6x, a, 10x, a)') 'polar_split:', trim(polar_split)
   write(ymlout,'(6x, a, 10x, a)') 'prefix:', trim(prefix)
   write(ymlout,'(6x, a, 10x, es23.16)') 'retol:', retol
   write(ymlout,'(6x, a, 10x, a)') 'sampling:', trim(sampling)
   write(ymlout,'(6x, a, 10x, a)') 'solver:', trim(solver)
   write(ymlout,'(6x, a, 10x, es23.16)') 'spectral_emax:', spectral_emax
   write(ymlout,'(6x, a, 10x, es23.16)') 'spectral_emin:', spectral_emin
   write(ymlout,'(6x, a, 10x, i10)') 'spectral_np:', spectral_np
   write(ymlout,'(6x, a, 10x, a)') 'sun_method:', trim(sun_method)
   write(ymlout,'(6x, a, 10x, i10)') 'sundials_mxsteps:', sundials_mxsteps
   write(ymlout,'(6x, a, 10x, es23.16)') 'time_step:', time_step
   write(ymlout,'(6x, a, 10x, a)') 'tmp_dir:', trim(tmp_dir)
   write(ymlout,'(6x, a, 10x, es23.16)') 'trans_thr:', trans_thr
   write(ymlout,'(6x, a, 10x, a)') 'use_mem:', python_bool(use_mem)
   write(ymlout,'(6x, a, 10x, a)') 'yaml_fname:', trim(yaml_fname)

end subroutine auto_output_afterconv_to_yaml

! the "before conversion" variabls has not been broadcast to other nodes, so it can just be used in master (io) node.
subroutine auto_output_beforeconv_to_yaml()
   implicit none
   write(ymlout,'(6x, a, 10x, es23.16)') 'abstol_c:', abstol_c_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'abstol_ph:', abstol_ph_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'adapt_smear_eph:', python_bool(adapt_smear_eph_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'adapt_smear_phph:', python_bool(adapt_smear_phph_beforeconv)
   write(ymlout,'(6x, a, 10x, i10)') 'band_max:', band_max_beforeconv
   write(ymlout,'(6x, a, 10x, i10)') 'band_min:', band_min_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_acc_thr:', boltz_acc_thr_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_de:', boltz_de_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_de_ph:', boltz_de_ph_beforeconv
   write(ymlout,'(6x, a, 10x, "[",3(es23.16,","2x),"]")') 'boltz_efield:', boltz_efield_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_emax:', boltz_emax_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_emin:', boltz_emin_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'boltz_init_dist:', trim(boltz_init_dist_beforeconv)
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_init_e0:', boltz_init_e0_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'boltz_init_smear:', boltz_init_smear_beforeconv
   write(ymlout,'(6x, a, 10x, "[",3(i10,","2x),"]")') 'boltz_kdim:', boltz_kdim_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'boltz_norm_dist:', python_bool(boltz_norm_dist_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'boltz_norm_energy:', python_bool(boltz_norm_energy_beforeconv)
   write(ymlout,'(6x, a, 10x, i10)') 'boltz_nstep:', boltz_nstep_beforeconv
   write(ymlout,'(6x, a, 10x, i10)') 'boltz_nstep_min:', boltz_nstep_min_beforeconv
   write(ymlout,'(6x, a, 10x, "[",3(i10,","2x),"]")') 'boltz_qdim:', boltz_qdim_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'calc_mode:', trim(calc_mode_beforeconv)
   write(ymlout,'(6x, a, 10x, es23.16)') 'cauchy_scale:', cauchy_scale_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'cum_de:', cum_de_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'cum_inner_emax:', cum_inner_emax_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'cum_inner_emin:', cum_inner_emin_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'cum_outer_emax:', cum_outer_emax_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'cum_outer_emin:', cum_outer_emin_beforeconv
   write(ymlout,'(6x, a, 10x, i10)') 'cum_outer_np:', cum_outer_np_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'debug:', python_bool(debug_beforeconv)
   write(ymlout,'(6x, a, 10x, es23.16)') 'delta_smear:', delta_smear_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'delta_smear_ph:', delta_smear_ph_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'divide_grid:', python_bool(divide_grid_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'dyna_phph:', python_bool(dyna_phph_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'find_efermi:', python_bool(find_efermi_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'fklist:', trim(fklist_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'fqlist:', trim(fqlist_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'ftemper:', trim(ftemper_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'full_ite:', python_bool(full_ite_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'hole:', python_bool(hole_beforeconv)
   write(ymlout,'(6x, a, 10x, es23.16)') 'hs:', hs_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'load_scatter_eph:', python_bool(load_scatter_eph_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'load_scatter_ph3:', python_bool(load_scatter_ph3_beforeconv)
   write(ymlout,'(6x, a, 10x, i10)') 'nphstep:', nphstep_beforeconv
   write(ymlout,'(6x, a, 10x, i10)') 'nsamples:', nsamples_beforeconv
   write(ymlout,'(6x, a, 10x, i10)') 'output_nstep:', output_nstep_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'phfreq_cutoff:', phfreq_cutoff_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'phfreq_cutoff_ph:', phfreq_cutoff_ph_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'polar_split:', trim(polar_split_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'prefix:', trim(prefix_beforeconv)
   write(ymlout,'(6x, a, 10x, es23.16)') 'retol:', retol_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'sampling:', trim(sampling_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'solver:', trim(solver_beforeconv)
   write(ymlout,'(6x, a, 10x, es23.16)') 'spectral_emax:', spectral_emax_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'spectral_emin:', spectral_emin_beforeconv
   write(ymlout,'(6x, a, 10x, i10)') 'spectral_np:', spectral_np_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'sun_method:', trim(sun_method_beforeconv)
   write(ymlout,'(6x, a, 10x, i10)') 'sundials_mxsteps:', sundials_mxsteps_beforeconv
   write(ymlout,'(6x, a, 10x, es23.16)') 'time_step:', time_step_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'tmp_dir:', trim(tmp_dir_beforeconv)
   write(ymlout,'(6x, a, 10x, es23.16)') 'trans_thr:', trans_thr_beforeconv
   write(ymlout,'(6x, a, 10x, a)') 'use_mem:', python_bool(use_mem_beforeconv)
   write(ymlout,'(6x, a, 10x, a)') 'yaml_fname:', trim(yaml_fname_beforeconv)

end subroutine auto_output_beforeconv_to_yaml

end module perturbo_autogen_output_yaml
